name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - mkirolos-safco
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact-name
    attributes:
      label: Contact Name
      description: Safco Employee name
      placeholder: e.g Mario Kirolos
    validations:
      required: true
  - type: input
    id: contact-email
    attributes:
      label: Contact Email
      description: Safco Employee email
      placeholder: e.g mkirolos@safcodental.com
    validations:
      required: true
  - type: input
    id: date-of-issue
    attributes:
      label: Date of Issue
      description: When the first time you saw this happening
    validations:
      required: true  
  - type: dropdown
    id: headline
    attributes:
      label: Issue Headline
      description: Please Choose from below what category this issue is about.
      multiple: false
      options:
        - Login
        - Search
        - Cart
        - Promo
        - Navigation
        - Others
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: related-project
    attributes:
      label: Related Project
      description: Where did you see this issue?
      options:
        - Main Website
        - Beta
        - Hubspot
        - Internal App
        - Background Process
      default: 0
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How fast this bug should be fixed?
      options:
        - High
        - Medium
        - Low
      default: 2
    validations:
      required: true
  - type: input
    id: customer-data
    attributes:
      label: Customer Email Address or Account number
      description: Customer reported this issue information
      placeholder: e.g 30007
    validations:
      required: true
  - type: input
    id: order-number
    attributes:
      label: Order number
      description: If Customer has a related order for the bug
      placeholder: e.g 123456
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce the issue
      description: Please put in steps how can we reproduce the issue you're referring to.
      placeholder: "1. Go to https://www.safcodental.com \n
      2. Hover over Products Menu \n
      3. Unable to see the list while logged in. \n\n
      you can also upload any screenshots here."